-- Logs begin at Tue 2019-08-13 17:08:21 IST, end at Tue 2019-08-13 17:49:56 IST. --
Aug 13 17:23:36 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:23:36 vishwanath systemd[1]: kubelet.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Aug 13 17:23:36 vishwanath systemd[1]: Stopping kubelet: The Kubernetes Node Agent...
Aug 13 17:23:36 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:23:36 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:23:36 vishwanath kubelet[13269]: F0813 17:23:36.755005   13269 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:23:36 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:23:36 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:23:46 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:23:46 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 1.
Aug 13 17:23:46 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:23:46 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:23:47 vishwanath kubelet[13392]: F0813 17:23:47.067034   13392 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:23:47 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:23:47 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:23:57 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:23:57 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 2.
Aug 13 17:23:57 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:23:57 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:23:57 vishwanath kubelet[13422]: F0813 17:23:57.280642   13422 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:23:57 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:23:57 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:24:07 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:24:07 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 3.
Aug 13 17:24:07 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:24:07 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:24:07 vishwanath kubelet[13454]: F0813 17:24:07.548620   13454 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:24:07 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:24:07 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:24:17 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:24:17 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 4.
Aug 13 17:24:17 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:24:17 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:24:17 vishwanath kubelet[13488]: F0813 17:24:17.809137   13488 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:24:17 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:24:17 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:24:27 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:24:27 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 5.
Aug 13 17:24:27 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:24:27 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:24:28 vishwanath kubelet[13521]: F0813 17:24:28.053427   13521 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:24:28 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:24:28 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:24:38 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:24:38 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 6.
Aug 13 17:24:38 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:24:38 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:24:38 vishwanath kubelet[13560]: F0813 17:24:38.283102   13560 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:24:38 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:24:38 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:24:48 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:24:48 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 7.
Aug 13 17:24:48 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:24:48 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:24:48 vishwanath kubelet[13594]: F0813 17:24:48.599228   13594 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:24:48 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:24:48 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:24:58 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:24:58 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 8.
Aug 13 17:24:58 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:24:58 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:24:58 vishwanath kubelet[13719]: F0813 17:24:58.809257   13719 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:24:58 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:24:58 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:25:08 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:25:08 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 9.
Aug 13 17:25:08 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:25:08 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:25:09 vishwanath kubelet[13761]: F0813 17:25:09.055917   13761 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:25:09 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:25:09 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:25:19 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:25:19 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 10.
Aug 13 17:25:19 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:25:19 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:25:19 vishwanath kubelet[13830]: F0813 17:25:19.332548   13830 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:25:19 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:25:19 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:25:29 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:25:29 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 11.
Aug 13 17:25:29 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:25:29 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:25:29 vishwanath kubelet[13902]: F0813 17:25:29.567157   13902 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:25:29 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:25:29 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:25:39 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:25:39 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 12.
Aug 13 17:25:39 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:25:39 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:25:39 vishwanath kubelet[14004]: F0813 17:25:39.795831   14004 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:25:39 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:25:39 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:25:49 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:25:49 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 13.
Aug 13 17:25:49 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:25:49 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:25:50 vishwanath kubelet[14109]: F0813 17:25:50.038440   14109 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:25:50 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:25:50 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:26:00 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:26:00 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 14.
Aug 13 17:26:00 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:26:00 vishwanath kubelet[14162]: F0813 17:26:00.287392   14162 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:26:00 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:26:00 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:26:00 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:26:10 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:26:10 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 15.
Aug 13 17:26:10 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:26:10 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:26:10 vishwanath kubelet[14255]: F0813 17:26:10.606052   14255 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Aug 13 17:26:10 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:26:10 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:26:14 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:26:14 vishwanath systemd[1]: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf:10: Invalid environment assignment, ignoring: ”cgroup-driver=systemd/cgroup-driver=cgroupfs”
Aug 13 17:26:14 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:26:14 vishwanath kubelet[14340]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 13 17:26:14 vishwanath kubelet[14340]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 13 17:26:14 vishwanath kubelet[14340]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 13 17:26:14 vishwanath kubelet[14340]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 13 17:26:16 vishwanath kubelet[14340]: F0813 17:26:16.181876   14340 server.go:253] unable to load client CA file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory
Aug 13 17:26:16 vishwanath systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 13 17:26:16 vishwanath systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 13 17:26:26 vishwanath systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Aug 13 17:26:26 vishwanath systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 16.
Aug 13 17:26:26 vishwanath systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 13 17:26:26 vishwanath systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 13 17:26:26 vishwanath kubelet[14385]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 13 17:26:26 vishwanath kubelet[14385]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 13 17:26:26 vishwanath kubelet[14385]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 13 17:26:26 vishwanath kubelet[14385]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.685125   14385 server.go:425] Version: v1.15.2
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.692319   14385 plugins.go:103] No cloud provider specified.
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.692963   14385 server.go:791] Client rotation is on, will bootstrap in background
Aug 13 17:26:26 vishwanath kubelet[14385]: E0813 17:26:26.738145   14385 certificate_manager.go:400] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post https://10.0.2.15:6443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.766548   14385 server.go:661] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.767421   14385 container_manager_linux.go:261] container manager verified user specified cgroup-root exists: []
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.767584   14385 container_manager_linux.go:266] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>} {Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>}]} QOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s ExperimentalPodPidsLimit:-1 EnforceCPULimits:true CPUCFSQuotaPeriod:100ms}
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.768479   14385 container_manager_linux.go:286] Creating device plugin manager: true
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.768723   14385 state_mem.go:36] [cpumanager] initializing new in-memory state store
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.784940   14385 kubelet.go:281] Adding pod path: /etc/kubernetes/manifests
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.785294   14385 kubelet.go:306] Watching apiserver
Aug 13 17:26:26 vishwanath kubelet[14385]: E0813 17:26:26.786821   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.0.2.15:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:26 vishwanath kubelet[14385]: E0813 17:26:26.787604   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.0.2.15:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:26 vishwanath kubelet[14385]: E0813 17:26:26.788289   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://10.0.2.15:6443/api/v1/nodes?fieldSelector=metadata.name%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.825368   14385 client.go:75] Connecting to docker on unix:///var/run/docker.sock
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.825417   14385 client.go:104] Start docker client with request timeout=2m0s
Aug 13 17:26:26 vishwanath kubelet[14385]: W0813 17:26:26.831630   14385 docker_service.go:561] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.831672   14385 docker_service.go:238] Hairpin mode set to "hairpin-veth"
Aug 13 17:26:26 vishwanath kubelet[14385]: W0813 17:26:26.831820   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:26:26 vishwanath kubelet[14385]: W0813 17:26:26.834382   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:26:26 vishwanath kubelet[14385]: W0813 17:26:26.834698   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.834703   14385 docker_service.go:253] Docker cri networking managed by cni
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.844350   14385 docker_service.go:258] Docker Info: &{ID:IH5Q:JJZU:FDTH:K7PA:H7KI:DQ4O:R4KL:XACZ:FDVR:RKWD:LVNF:XDLM Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Images:7 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true]] SystemStatus:[] Plugins:{Volume:[local] Network:[bridge host macvlan null overlay] Authorization:[] Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:false KernelMemory:true KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:false IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6tables:true Debug:false NFd:24 OomKillDisable:true NGoroutines:39 SystemTime:2019-08-13T17:26:26.836526011+05:30 LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:0 KernelVersion:4.18.0-15-generic OperatingSystem:Ubuntu 18.04.2 LTS OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:0xc00081df10 NCPU:3 MemTotal:4136099840 GenericResources:[] DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:vishwanath Labels:[] ExperimentalBuild:false ServerVersion:18.09.7 ClusterStore: ClusterAdvertise: Runtimes:map[runc:{Path:runc Args:[]}] DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:[] Nodes:0 Managers:0 Cluster:<nil> Warnings:[]} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID: Expected:} RuncCommit:{ID:N/A Expected:N/A} InitCommit:{ID:v0.18.0 Expected:fec3683b971d9c3ef73f284f176672c44b448662} SecurityOptions:[name=apparmor name=seccomp,profile=default] ProductLicense: Warnings:[WARNING: No swap limit support]}
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.844429   14385 docker_service.go:271] Setting cgroupDriver to cgroupfs
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.859849   14385 remote_runtime.go:59] parsed scheme: ""
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.859884   14385 remote_runtime.go:59] scheme "" not registered, fallback to default scheme
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.859931   14385 remote_image.go:50] parsed scheme: ""
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.859950   14385 remote_image.go:50] scheme "" not registered, fallback to default scheme
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.860442   14385 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/run/dockershim.sock 0  <nil>}]
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.860475   14385 clientconn.go:796] ClientConn switching balancer to "pick_first"
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.860499   14385 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{/var/run/dockershim.sock 0  <nil>}]
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.860523   14385 clientconn.go:796] ClientConn switching balancer to "pick_first"
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.860547   14385 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc0007fc6d0, CONNECTING
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.861163   14385 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc0009b5190, CONNECTING
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.861261   14385 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc0007fc6d0, READY
Aug 13 17:26:26 vishwanath kubelet[14385]: I0813 17:26:26.861325   14385 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc0009b5190, READY
Aug 13 17:26:27 vishwanath kubelet[14385]: E0813 17:26:27.790780   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.0.2.15:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:27 vishwanath kubelet[14385]: E0813 17:26:27.791107   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.0.2.15:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:27 vishwanath kubelet[14385]: E0813 17:26:27.793894   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://10.0.2.15:6443/api/v1/nodes?fieldSelector=metadata.name%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:28 vishwanath kubelet[14385]: E0813 17:26:28.793457   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.0.2.15:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:28 vishwanath kubelet[14385]: E0813 17:26:28.795957   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.0.2.15:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:28 vishwanath kubelet[14385]: E0813 17:26:28.797646   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://10.0.2.15:6443/api/v1/nodes?fieldSelector=metadata.name%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:28 vishwanath kubelet[14385]: E0813 17:26:28.918368   14385 certificate_manager.go:400] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post https://10.0.2.15:6443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:29 vishwanath kubelet[14385]: E0813 17:26:29.796727   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.0.2.15:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:29 vishwanath kubelet[14385]: E0813 17:26:29.798978   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.0.2.15:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:29 vishwanath kubelet[14385]: E0813 17:26:29.801272   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://10.0.2.15:6443/api/v1/nodes?fieldSelector=metadata.name%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:29 vishwanath kubelet[14385]: E0813 17:26:29.928695   14385 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
Aug 13 17:26:29 vishwanath kubelet[14385]:         For verbose messaging see aws.Config.CredentialsChainVerboseErrors
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.939501   14385 kuberuntime_manager.go:205] Container runtime docker initialized, version: 18.09.7, apiVersion: 1.39.0
Aug 13 17:26:29 vishwanath kubelet[14385]: W0813 17:26:29.941620   14385 probe.go:268] Flexvolume plugin directory at /usr/libexec/kubernetes/kubelet-plugins/volume/exec/ does not exist. Recreating.
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.950901   14385 server.go:1083] Started kubelet
Aug 13 17:26:29 vishwanath kubelet[14385]: E0813 17:26:29.952768   14385 event.go:249] Unable to write event: 'Post https://10.0.2.15:6443/api/v1/namespaces/default/events: dial tcp 10.0.2.15:6443: connect: connection refused' (may retry after sleeping)
Aug 13 17:26:29 vishwanath kubelet[14385]: E0813 17:26:29.952932   14385 kubelet.go:1293] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.954596   14385 server.go:144] Starting to listen on 0.0.0.0:10250
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.959961   14385 server.go:350] Adding debug handlers to kubelet server.
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.960847   14385 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.972308   14385 status_manager.go:152] Starting to sync pod status with apiserver
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.972628   14385 volume_manager.go:243] Starting Kubelet Volume Manager
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.972679   14385 kubelet.go:1805] Starting kubelet main sync loop.
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.972770   14385 kubelet.go:1822] skipping pod synchronization - [container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.976296   14385 desired_state_of_world_populator.go:130] Desired state populator starts to run
Aug 13 17:26:29 vishwanath kubelet[14385]: E0813 17:26:29.977772   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://10.0.2.15:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:29 vishwanath kubelet[14385]: E0813 17:26:29.978549   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://10.0.2.15:6443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:29 vishwanath kubelet[14385]: E0813 17:26:29.980673   14385 controller.go:115] failed to ensure node lease exists, will retry in 200ms, error: Get https://10.0.2.15:6443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/vishwanath?timeout=10s: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:29 vishwanath kubelet[14385]: E0813 17:26:29.983441   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.999442   14385 clientconn.go:440] parsed scheme: "unix"
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.999544   14385 clientconn.go:440] scheme "unix" not registered, fallback to default scheme
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.999606   14385 asm_amd64.s:1337] ccResolverWrapper: sending new addresses to cc: [{unix:///run/containerd/containerd.sock 0  <nil>}]
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.999628   14385 clientconn.go:796] ClientConn switching balancer to "pick_first"
Aug 13 17:26:29 vishwanath kubelet[14385]: I0813 17:26:29.999688   14385 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc000a8a6a0, CONNECTING
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.001762   14385 balancer_conn_wrappers.go:131] pickfirstBalancer: HandleSubConnStateChange: 0xc000a8a6a0, READY
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.073621   14385 kubelet.go:1822] skipping pod synchronization - container runtime status check may not have completed yet
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.074586   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.074649   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.078140   14385 kubelet_node_status.go:72] Attempting to register node vishwanath
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.078951   14385 kubelet_node_status.go:94] Unable to register node "vishwanath" with API server: Post https://10.0.2.15:6443/api/v1/nodes: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.150243   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.153316   14385 cpu_manager.go:155] [cpumanager] starting with none policy
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.153338   14385 cpu_manager.go:156] [cpumanager] reconciling every 10s
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.153397   14385 policy_none.go:42] [cpumanager] none policy: Start
Aug 13 17:26:30 vishwanath kubelet[14385]: W0813 17:26:30.192297   14385 manager.go:546] Failed to retrieve checkpoint for "kubelet_internal_checkpoint": checkpoint is not found
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.192618   14385 plugin_manager.go:116] Starting Kubelet Plugin Manager
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.193390   14385 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: node "vishwanath" not found
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.199040   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.199323   14385 controller.go:115] failed to ensure node lease exists, will retry in 400ms, error: Get https://10.0.2.15:6443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/vishwanath?timeout=10s: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.276365   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.279694   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.296282   14385 kubelet_node_status.go:72] Attempting to register node vishwanath
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.300110   14385 kubelet_node_status.go:94] Unable to register node "vishwanath" with API server: Post https://10.0.2.15:6443/api/v1/nodes: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.301131   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.303624   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "etc-ca-certificates" (UniqueName: "kubernetes.io/host-path/06dfe7231706fdb8f0a23e8fd07854f0-etc-ca-certificates") pod "kube-controller-manager-vishwanath" (UID: "06dfe7231706fdb8f0a23e8fd07854f0")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.305612   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "etc-pki" (UniqueName: "kubernetes.io/host-path/06dfe7231706fdb8f0a23e8fd07854f0-etc-pki") pod "kube-controller-manager-vishwanath" (UID: "06dfe7231706fdb8f0a23e8fd07854f0")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.306652   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "k8s-certs" (UniqueName: "kubernetes.io/host-path/06dfe7231706fdb8f0a23e8fd07854f0-k8s-certs") pod "kube-controller-manager-vishwanath" (UID: "06dfe7231706fdb8f0a23e8fd07854f0")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.307558   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "kubeconfig" (UniqueName: "kubernetes.io/host-path/06dfe7231706fdb8f0a23e8fd07854f0-kubeconfig") pod "kube-controller-manager-vishwanath" (UID: "06dfe7231706fdb8f0a23e8fd07854f0")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.308724   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "usr-local-share-ca-certificates" (UniqueName: "kubernetes.io/host-path/06dfe7231706fdb8f0a23e8fd07854f0-usr-local-share-ca-certificates") pod "kube-controller-manager-vishwanath" (UID: "06dfe7231706fdb8f0a23e8fd07854f0")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.311900   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "usr-share-ca-certificates" (UniqueName: "kubernetes.io/host-path/06dfe7231706fdb8f0a23e8fd07854f0-usr-share-ca-certificates") pod "kube-controller-manager-vishwanath" (UID: "06dfe7231706fdb8f0a23e8fd07854f0")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.312867   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "ca-certs" (UniqueName: "kubernetes.io/host-path/06dfe7231706fdb8f0a23e8fd07854f0-ca-certs") pod "kube-controller-manager-vishwanath" (UID: "06dfe7231706fdb8f0a23e8fd07854f0")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.313650   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.313952   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: W0813 17:26:30.329161   14385 status_manager.go:485] Failed to get status for pod "kube-controller-manager-vishwanath_kube-system(06dfe7231706fdb8f0a23e8fd07854f0)": Get https://10.0.2.15:6443/api/v1/namespaces/kube-system/pods/kube-controller-manager-vishwanath: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.335114   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.336963   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.349943   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.350747   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: W0813 17:26:30.354442   14385 status_manager.go:485] Failed to get status for pod "kube-scheduler-vishwanath_kube-system(abfcb4f52e957b11256c1f6841d49700)": Get https://10.0.2.15:6443/api/v1/namespaces/kube-system/pods/kube-scheduler-vishwanath: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.358259   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: W0813 17:26:30.360718   14385 status_manager.go:485] Failed to get status for pod "etcd-vishwanath_kube-system(ba0b24f1d4687f5485411f9f6c1626c4)": Get https://10.0.2.15:6443/api/v1/namespaces/kube-system/pods/etcd-vishwanath: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: W0813 17:26:30.377705   14385 status_manager.go:485] Failed to get status for pod "kube-apiserver-vishwanath_kube-system(8555a9d51be4482b6d8af73bc20a2098)": Get https://10.0.2.15:6443/api/v1/namespaces/kube-system/pods/kube-apiserver-vishwanath: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.401662   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.414398   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "etcd-data" (UniqueName: "kubernetes.io/host-path/ba0b24f1d4687f5485411f9f6c1626c4-etcd-data") pod "etcd-vishwanath" (UID: "ba0b24f1d4687f5485411f9f6c1626c4")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.414669   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "usr-share-ca-certificates" (UniqueName: "kubernetes.io/host-path/8555a9d51be4482b6d8af73bc20a2098-usr-share-ca-certificates") pod "kube-apiserver-vishwanath" (UID: "8555a9d51be4482b6d8af73bc20a2098")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.414998   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "kubeconfig" (UniqueName: "kubernetes.io/host-path/abfcb4f52e957b11256c1f6841d49700-kubeconfig") pod "kube-scheduler-vishwanath" (UID: "abfcb4f52e957b11256c1f6841d49700")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.415369   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "etcd-certs" (UniqueName: "kubernetes.io/host-path/ba0b24f1d4687f5485411f9f6c1626c4-etcd-certs") pod "etcd-vishwanath" (UID: "ba0b24f1d4687f5485411f9f6c1626c4")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.415759   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "k8s-certs" (UniqueName: "kubernetes.io/host-path/8555a9d51be4482b6d8af73bc20a2098-k8s-certs") pod "kube-apiserver-vishwanath" (UID: "8555a9d51be4482b6d8af73bc20a2098")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.415959   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "etc-ca-certificates" (UniqueName: "kubernetes.io/host-path/8555a9d51be4482b6d8af73bc20a2098-etc-ca-certificates") pod "kube-apiserver-vishwanath" (UID: "8555a9d51be4482b6d8af73bc20a2098")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.416300   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "etc-pki" (UniqueName: "kubernetes.io/host-path/8555a9d51be4482b6d8af73bc20a2098-etc-pki") pod "kube-apiserver-vishwanath" (UID: "8555a9d51be4482b6d8af73bc20a2098")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.416588   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "usr-local-share-ca-certificates" (UniqueName: "kubernetes.io/host-path/8555a9d51be4482b6d8af73bc20a2098-usr-local-share-ca-certificates") pod "kube-apiserver-vishwanath" (UID: "8555a9d51be4482b6d8af73bc20a2098")
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.416855   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "ca-certs" (UniqueName: "kubernetes.io/host-path/8555a9d51be4482b6d8af73bc20a2098-ca-certs") pod "kube-apiserver-vishwanath" (UID: "8555a9d51be4482b6d8af73bc20a2098")
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.504355   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.601508   14385 controller.go:115] failed to ensure node lease exists, will retry in 800ms, error: Get https://10.0.2.15:6443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/vishwanath?timeout=10s: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.606197   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.706113   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.706659   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:30 vishwanath kubelet[14385]: I0813 17:26:30.714244   14385 kubelet_node_status.go:72] Attempting to register node vishwanath
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.714643   14385 kubelet_node_status.go:94] Unable to register node "vishwanath" with API server: Post https://10.0.2.15:6443/api/v1/nodes: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.798474   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.0.2.15:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.799480   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.0.2.15:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.802290   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://10.0.2.15:6443/api/v1/nodes?fieldSelector=metadata.name%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.807750   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.909093   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:30 vishwanath kubelet[14385]: E0813 17:26:30.998302   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://10.0.2.15:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.010325   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.111996   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.198243   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://10.0.2.15:6443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.214480   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.315996   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.405633   14385 controller.go:115] failed to ensure node lease exists, will retry in 1.6s, error: Get https://10.0.2.15:6443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/vishwanath?timeout=10s: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.416229   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:31 vishwanath kubelet[14385]: I0813 17:26:31.514776   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.516418   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:31 vishwanath kubelet[14385]: I0813 17:26:31.518222   14385 kubelet_node_status.go:72] Attempting to register node vishwanath
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.518646   14385 kubelet_node_status.go:94] Unable to register node "vishwanath" with API server: Post https://10.0.2.15:6443/api/v1/nodes: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.617424   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.717647   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.804239   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://10.0.2.15:6443/api/v1/nodes?fieldSelector=metadata.name%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.804379   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.0.2.15:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.831498   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:31 vishwanath kubelet[14385]: W0813 17:26:31.834874   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.937753   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:31 vishwanath kubelet[14385]: E0813 17:26:31.998763   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.0.2.15:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.039541   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.139888   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.195988   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://10.0.2.15:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.241813   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:32 vishwanath kubelet[14385]: I0813 17:26:32.249271   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:32 vishwanath kubelet[14385]: W0813 17:26:32.258923   14385 pod_container_deletor.go:75] Container "675e5e2fc31c5f51d78a17a00e8b1c506e59819180a0659d936f0e316c3a2bb6" not found in pod's containers
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.278469   14385 event.go:249] Unable to write event: 'Post https://10.0.2.15:6443/api/v1/namespaces/default/events: dial tcp 10.0.2.15:6443: connect: connection refused' (may retry after sleeping)
Aug 13 17:26:32 vishwanath kubelet[14385]: I0813 17:26:32.341149   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.344981   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:32 vishwanath kubelet[14385]: W0813 17:26:32.389881   14385 pod_container_deletor.go:75] Container "0a907eb3dfe69f3f8dac0766d3d138268b13fb56ed3ae070b7aa2334022460a7" not found in pod's containers
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.401058   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://10.0.2.15:6443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:32 vishwanath kubelet[14385]: I0813 17:26:32.414442   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:32 vishwanath kubelet[14385]: W0813 17:26:32.439645   14385 pod_container_deletor.go:75] Container "1abc850f8aa476abf1ccd3da3a4f50e638476637eef3b4d97cdd74fc683ce3c1" not found in pod's containers
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.453250   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:32 vishwanath kubelet[14385]: I0813 17:26:32.503119   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:32 vishwanath kubelet[14385]: W0813 17:26:32.531577   14385 pod_container_deletor.go:75] Container "ffa92f5f171d552887060033810e8bdd67bf5de0b1af7c9777a7402cec360c07" not found in pod's containers
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.553739   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.657650   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.758882   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.810193   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.0.2.15:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.810387   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://10.0.2.15:6443/api/v1/nodes?fieldSelector=metadata.name%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.859236   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:32 vishwanath kubelet[14385]: E0813 17:26:32.959540   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.008401   14385 controller.go:115] failed to ensure node lease exists, will retry in 3.2s, error: Get https://10.0.2.15:6443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/vishwanath?timeout=10s: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.008579   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.0.2.15:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.059985   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: I0813 17:26:33.118891   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:33 vishwanath kubelet[14385]: I0813 17:26:33.135141   14385 kubelet_node_status.go:72] Attempting to register node vishwanath
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.135846   14385 certificate_manager.go:400] Failed while requesting a signed certificate from the master: cannot create certificate signing request: Post https://10.0.2.15:6443/apis/certificates.k8s.io/v1beta1/certificatesigningrequests: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.160171   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.196015   14385 kubelet_node_status.go:94] Unable to register node "vishwanath" with API server: Post https://10.0.2.15:6443/api/v1/nodes: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.265124   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.367088   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.396663   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://10.0.2.15:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.467416   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.567707   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.601294   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://10.0.2.15:6443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.668565   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.768833   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: I0813 17:26:33.800478   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:33 vishwanath kubelet[14385]: W0813 17:26:33.809697   14385 status_manager.go:485] Failed to get status for pod "kube-apiserver-vishwanath_kube-system(8555a9d51be4482b6d8af73bc20a2098)": Get https://10.0.2.15:6443/api/v1/namespaces/kube-system/pods/kube-apiserver-vishwanath: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:33 vishwanath kubelet[14385]: I0813 17:26:33.814309   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.879433   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.979997   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:33 vishwanath kubelet[14385]: E0813 17:26:33.995987   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.0.2.15:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.080587   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.181112   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.195731   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://10.0.2.15:6443/api/v1/nodes?fieldSelector=metadata.name%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.281708   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.382243   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:34 vishwanath kubelet[14385]: W0813 17:26:34.395750   14385 status_manager.go:485] Failed to get status for pod "etcd-vishwanath_kube-system(ba0b24f1d4687f5485411f9f6c1626c4)": Get https://10.0.2.15:6443/api/v1/namespaces/kube-system/pods/etcd-vishwanath: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.482834   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.583384   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.596144   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.0.2.15:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.684455   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.785757   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.796780   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://10.0.2.15:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:34 vishwanath kubelet[14385]: I0813 17:26:34.831759   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:34 vishwanath kubelet[14385]: I0813 17:26:34.858975   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:34 vishwanath kubelet[14385]: I0813 17:26:34.879342   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.886838   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:34 vishwanath kubelet[14385]: I0813 17:26:34.896426   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.987566   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:34 vishwanath kubelet[14385]: E0813 17:26:34.995762   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://10.0.2.15:6443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.088156   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.189224   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.193748   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:26:35 vishwanath kubelet[14385]: W0813 17:26:35.195761   14385 status_manager.go:485] Failed to get status for pod "kube-controller-manager-vishwanath_kube-system(06dfe7231706fdb8f0a23e8fd07854f0)": Get https://10.0.2.15:6443/api/v1/namespaces/kube-system/pods/kube-controller-manager-vishwanath: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.290243   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.390788   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.396009   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.0.2.15:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.491401   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.591908   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.596777   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://10.0.2.15:6443/api/v1/nodes?fieldSelector=metadata.name%3Dvishwanath&limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.693052   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.793718   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:35 vishwanath kubelet[14385]: W0813 17:26:35.795852   14385 status_manager.go:485] Failed to get status for pod "kube-scheduler-vishwanath_kube-system(abfcb4f52e957b11256c1f6841d49700)": Get https://10.0.2.15:6443/api/v1/namespaces/kube-system/pods/kube-scheduler-vishwanath: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.894531   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:35 vishwanath kubelet[14385]: I0813 17:26:35.902680   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:35 vishwanath kubelet[14385]: I0813 17:26:35.903318   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:35 vishwanath kubelet[14385]: I0813 17:26:35.903861   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:35 vishwanath kubelet[14385]: I0813 17:26:35.904482   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.994968   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:35 vishwanath kubelet[14385]: E0813 17:26:35.996095   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.0.2.15:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 10.0.2.15:6443: connect: connection refused
Aug 13 17:26:36 vishwanath kubelet[14385]: E0813 17:26:36.095681   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:36 vishwanath kubelet[14385]: E0813 17:26:36.196755   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:36 vishwanath kubelet[14385]: E0813 17:26:36.297345   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:36 vishwanath kubelet[14385]: I0813 17:26:36.396232   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:36 vishwanath kubelet[14385]: E0813 17:26:36.398048   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:36 vishwanath kubelet[14385]: I0813 17:26:36.399793   14385 kubelet_node_status.go:72] Attempting to register node vishwanath
Aug 13 17:26:36 vishwanath kubelet[14385]: E0813 17:26:36.498425   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:36 vishwanath kubelet[14385]: E0813 17:26:36.598978   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:36 vishwanath kubelet[14385]: E0813 17:26:36.699585   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:36 vishwanath kubelet[14385]: E0813 17:26:36.800132   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:36 vishwanath kubelet[14385]: W0813 17:26:36.835296   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:26:36 vishwanath kubelet[14385]: E0813 17:26:36.900678   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:37 vishwanath kubelet[14385]: E0813 17:26:37.002215   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:37 vishwanath kubelet[14385]: E0813 17:26:37.103302   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:37 vishwanath kubelet[14385]: E0813 17:26:37.203797   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:37 vishwanath kubelet[14385]: E0813 17:26:37.304135   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:37 vishwanath kubelet[14385]: E0813 17:26:37.404540   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:37 vishwanath kubelet[14385]: E0813 17:26:37.507796   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:37 vishwanath kubelet[14385]: E0813 17:26:37.609103   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:37 vishwanath kubelet[14385]: E0813 17:26:37.709350   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:37 vishwanath kubelet[14385]: E0813 17:26:37.810853   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:37 vishwanath kubelet[14385]: E0813 17:26:37.911198   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:38 vishwanath kubelet[14385]: E0813 17:26:38.013110   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:38 vishwanath kubelet[14385]: E0813 17:26:38.114225   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:38 vishwanath kubelet[14385]: E0813 17:26:38.215095   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:38 vishwanath kubelet[14385]: E0813 17:26:38.315692   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:38 vishwanath kubelet[14385]: E0813 17:26:38.416785   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:38 vishwanath kubelet[14385]: E0813 17:26:38.517459   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:38 vishwanath kubelet[14385]: E0813 17:26:38.618018   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:38 vishwanath kubelet[14385]: E0813 17:26:38.718230   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:38 vishwanath kubelet[14385]: E0813 17:26:38.818469   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:38 vishwanath kubelet[14385]: E0813 17:26:38.918675   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:39 vishwanath kubelet[14385]: E0813 17:26:39.019587   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:39 vishwanath kubelet[14385]: E0813 17:26:39.120037   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:39 vishwanath kubelet[14385]: E0813 17:26:39.220224   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:39 vishwanath kubelet[14385]: E0813 17:26:39.320451   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:39 vishwanath kubelet[14385]: E0813 17:26:39.421236   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:39 vishwanath kubelet[14385]: E0813 17:26:39.521598   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:39 vishwanath kubelet[14385]: E0813 17:26:39.621920   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:39 vishwanath kubelet[14385]: E0813 17:26:39.722774   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:39 vishwanath kubelet[14385]: E0813 17:26:39.827051   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:39 vishwanath kubelet[14385]: E0813 17:26:39.927357   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.027626   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.128148   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.194130   14385 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.195614   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.228751   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.332744   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.444884   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.546085   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.646497   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.747065   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.848089   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:40 vishwanath kubelet[14385]: E0813 17:26:40.948572   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:41 vishwanath kubelet[14385]: E0813 17:26:41.048781   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:41 vishwanath kubelet[14385]: E0813 17:26:41.151745   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:41 vishwanath kubelet[14385]: E0813 17:26:41.253301   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:41 vishwanath kubelet[14385]: E0813 17:26:41.353824   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:41 vishwanath kubelet[14385]: E0813 17:26:41.454435   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:41 vishwanath kubelet[14385]: E0813 17:26:41.555716   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:41 vishwanath kubelet[14385]: E0813 17:26:41.656630   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:41 vishwanath kubelet[14385]: E0813 17:26:41.758008   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:41 vishwanath kubelet[14385]: W0813 17:26:41.835719   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:26:41 vishwanath kubelet[14385]: E0813 17:26:41.858604   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:41 vishwanath kubelet[14385]: E0813 17:26:41.959170   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:42 vishwanath kubelet[14385]: E0813 17:26:42.059398   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:42 vishwanath kubelet[14385]: E0813 17:26:42.159862   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:42 vishwanath kubelet[14385]: E0813 17:26:42.261371   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:42 vishwanath kubelet[14385]: E0813 17:26:42.362369   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:42 vishwanath kubelet[14385]: E0813 17:26:42.462980   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:42 vishwanath kubelet[14385]: E0813 17:26:42.563539   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:42 vishwanath kubelet[14385]: E0813 17:26:42.663794   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:42 vishwanath kubelet[14385]: E0813 17:26:42.764448   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:42 vishwanath kubelet[14385]: E0813 17:26:42.865331   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:42 vishwanath kubelet[14385]: E0813 17:26:42.965543   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:43 vishwanath kubelet[14385]: E0813 17:26:43.066083   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:43 vishwanath kubelet[14385]: E0813 17:26:43.168743   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:43 vishwanath kubelet[14385]: E0813 17:26:43.269134   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:43 vishwanath kubelet[14385]: E0813 17:26:43.370706   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:43 vishwanath kubelet[14385]: E0813 17:26:43.472258   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:43 vishwanath kubelet[14385]: E0813 17:26:43.572830   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:43 vishwanath kubelet[14385]: E0813 17:26:43.673471   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:43 vishwanath kubelet[14385]: E0813 17:26:43.773939   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:43 vishwanath kubelet[14385]: E0813 17:26:43.875527   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:43 vishwanath kubelet[14385]: E0813 17:26:43.975989   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:44 vishwanath kubelet[14385]: E0813 17:26:44.076830   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:44 vishwanath kubelet[14385]: E0813 17:26:44.177371   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:44 vishwanath kubelet[14385]: E0813 17:26:44.279125   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:44 vishwanath kubelet[14385]: E0813 17:26:44.380199   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:44 vishwanath kubelet[14385]: E0813 17:26:44.480723   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:44 vishwanath kubelet[14385]: E0813 17:26:44.581284   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:44 vishwanath kubelet[14385]: E0813 17:26:44.682829   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:44 vishwanath kubelet[14385]: E0813 17:26:44.783399   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:44 vishwanath kubelet[14385]: E0813 17:26:44.883970   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:44 vishwanath kubelet[14385]: E0813 17:26:44.984503   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.086040   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.186629   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.197533   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.287193   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.387822   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.488295   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.588873   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.689397   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.790458   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.891043   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:45 vishwanath kubelet[14385]: E0813 17:26:45.991580   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.092640   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.193705   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:46 vishwanath kubelet[14385]: I0813 17:26:46.197313   14385 trace.go:81] Trace[1813299150]: "Reflector k8s.io/client-go/informers/factory.go:133 ListAndWatch" (started: 2019-08-13 17:26:35.797381215 +0530 IST m=+9.383133227) (total time: 10.399885211s):
Aug 13 17:26:46 vishwanath kubelet[14385]: Trace[1813299150]: [10.399885211s] [10.399885211s] END
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.197654   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://10.0.2.15:6443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: net/http: TLS handshake timeout
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.209386   14385 controller.go:115] failed to ensure node lease exists, will retry in 6.4s, error: Get https://10.0.2.15:6443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/vishwanath?timeout=10s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.294270   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.395334   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:46 vishwanath kubelet[14385]: I0813 17:26:46.396069   14385 trace.go:81] Trace[1681052518]: "Reflector k8s.io/client-go/informers/factory.go:133 ListAndWatch" (started: 2019-08-13 17:26:35.996095319 +0530 IST m=+9.581847320) (total time: 10.399933651s):
Aug 13 17:26:46 vishwanath kubelet[14385]: Trace[1681052518]: [10.399933651s] [10.399933651s] END
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.396458   14385 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://10.0.2.15:6443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: net/http: TLS handshake timeout
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.496400   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:46 vishwanath kubelet[14385]: I0813 17:26:46.596634   14385 trace.go:81] Trace[880382431]: "Reflector k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47 ListAndWatch" (started: 2019-08-13 17:26:36.396552506 +0530 IST m=+9.982304497) (total time: 10.200047351s):
Aug 13 17:26:46 vishwanath kubelet[14385]: Trace[880382431]: [10.200047351s] [10.200047351s] END
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.597080   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://10.0.2.15:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dvishwanath&limit=500&resourceVersion=0: net/http: TLS handshake timeout
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.597254   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.697559   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.798137   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.799609   14385 kubelet_node_status.go:94] Unable to register node "vishwanath" with API server: Post https://10.0.2.15:6443/api/v1/nodes: net/http: TLS handshake timeout
Aug 13 17:26:46 vishwanath kubelet[14385]: W0813 17:26:46.836198   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.898969   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:46 vishwanath kubelet[14385]: I0813 17:26:46.996896   14385 trace.go:81] Trace[830064212]: "Reflector k8s.io/kubernetes/pkg/kubelet/kubelet.go:453 ListAndWatch" (started: 2019-08-13 17:26:36.597048925 +0530 IST m=+10.182800939) (total time: 10.399813682s):
Aug 13 17:26:46 vishwanath kubelet[14385]: Trace[830064212]: [10.399813682s] [10.399813682s] END
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.997704   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://10.0.2.15:6443/api/v1/nodes?fieldSelector=metadata.name%3Dvishwanath&limit=500&resourceVersion=0: net/http: TLS handshake timeout
Aug 13 17:26:46 vishwanath kubelet[14385]: E0813 17:26:46.999650   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:47 vishwanath kubelet[14385]: E0813 17:26:47.100279   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:47 vishwanath kubelet[14385]: I0813 17:26:47.196575   14385 trace.go:81] Trace[1712316671]: "Reflector k8s.io/kubernetes/pkg/kubelet/kubelet.go:444 ListAndWatch" (started: 2019-08-13 17:26:36.996340816 +0530 IST m=+10.582092802) (total time: 10.200191412s):
Aug 13 17:26:47 vishwanath kubelet[14385]: Trace[1712316671]: [10.200191412s] [10.200191412s] END
Aug 13 17:26:47 vishwanath kubelet[14385]: E0813 17:26:47.197095   14385 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://10.0.2.15:6443/api/v1/services?limit=500&resourceVersion=0: net/http: TLS handshake timeout
Aug 13 17:26:47 vishwanath kubelet[14385]: E0813 17:26:47.200816   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:47 vishwanath kubelet[14385]: E0813 17:26:47.301266   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:47 vishwanath kubelet[14385]: E0813 17:26:47.402482   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:47 vishwanath kubelet[14385]: E0813 17:26:47.503000   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:47 vishwanath kubelet[14385]: E0813 17:26:47.603735   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:47 vishwanath kubelet[14385]: E0813 17:26:47.704592   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:47 vishwanath kubelet[14385]: E0813 17:26:47.804847   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:47 vishwanath kubelet[14385]: E0813 17:26:47.905744   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:48 vishwanath kubelet[14385]: E0813 17:26:48.006258   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:48 vishwanath kubelet[14385]: E0813 17:26:48.107400   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:48 vishwanath kubelet[14385]: E0813 17:26:48.207885   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:48 vishwanath kubelet[14385]: E0813 17:26:48.309013   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:48 vishwanath kubelet[14385]: E0813 17:26:48.410569   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:48 vishwanath kubelet[14385]: E0813 17:26:48.512039   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:48 vishwanath kubelet[14385]: E0813 17:26:48.613720   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:48 vishwanath kubelet[14385]: E0813 17:26:48.715103   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:48 vishwanath kubelet[14385]: E0813 17:26:48.815644   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:48 vishwanath kubelet[14385]: E0813 17:26:48.916202   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:49 vishwanath kubelet[14385]: E0813 17:26:49.018226   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:49 vishwanath kubelet[14385]: E0813 17:26:49.119262   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:49 vishwanath kubelet[14385]: E0813 17:26:49.219855   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:49 vishwanath kubelet[14385]: E0813 17:26:49.320427   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:49 vishwanath kubelet[14385]: E0813 17:26:49.420717   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:49 vishwanath kubelet[14385]: E0813 17:26:49.521074   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:49 vishwanath kubelet[14385]: E0813 17:26:49.621663   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:49 vishwanath kubelet[14385]: E0813 17:26:49.723130   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:49 vishwanath kubelet[14385]: E0813 17:26:49.824536   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:49 vishwanath kubelet[14385]: E0813 17:26:49.926520   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.027458   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.128118   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.194638   14385 eviction_manager.go:247] eviction manager: failed to get summary stats: failed to get node info: node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.199958   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.228763   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.330200   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.431809   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.532281   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.632841   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.733463   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.835915   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.838545   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b11c4da5a", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b78aad85a, ext:3536472822, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b78aad85a, ext:3536472822, loc:(*time.Location)(0x781e740)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:50 vishwanath kubelet[14385]: I0813 17:26:50.858643   14385 reconciler.go:150] Reconciler: start to sync state
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.936641   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:50 vishwanath kubelet[14385]: E0813 17:26:50.955177   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c0dea", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node vishwanath status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a741ea, ext:3663822266, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a741ea, ext:3663822266, loc:(*time.Location)(0x781e740)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.030357   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c3579", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node vishwanath status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a76979, ext:3663832388, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a76979, ext:3663832388, loc:(*time.Location)(0x781e740)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.036957   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.086135   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c5684", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node vishwanath status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a78a84, ext:3663840849, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a78a84, ext:3663840849, loc:(*time.Location)(0x781e740)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.137691   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.165874   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c0dea", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node vishwanath status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a741ea, ext:3663822266, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b8922a613, ext:3739017678, loc:(*time.Location)(0x781e740)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.238369   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.240397   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c3579", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node vishwanath status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a76979, ext:3663832388, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b8922c6f2, ext:3739026092, loc:(*time.Location)(0x781e740)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.312248   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c5684", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node vishwanath status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a78a84, ext:3663840849, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b8922dee1, ext:3739032219, loc:(*time.Location)(0x781e740)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.340299   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.382271   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b203623d3", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeAllocatableEnforced", Message:"Updated Node Allocatable limit across pods", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b8b8157d3, ext:3778777999, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b8b8157d3, ext:3778777999, loc:(*time.Location)(0x781e740)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.441028   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.464110   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c0dea", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node vishwanath status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a741ea, ext:3663822266, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b9143f1f0, ext:3875417835, loc:(*time.Location)(0x781e740)}}, Count:3, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.544974   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.646662   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.724775   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c3579", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node vishwanath status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a76979, ext:3663832388, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b91453fb1, ext:3875503261, loc:(*time.Location)(0x781e740)}}, Count:3, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.747144   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:51 vishwanath kubelet[14385]: W0813 17:26:51.838403   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.848126   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:51 vishwanath kubelet[14385]: E0813 17:26:51.948644   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.049005   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.099753   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c5684", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node vishwanath status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a78a84, ext:3663840849, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b914a0d5b, ext:3875817969, loc:(*time.Location)(0x781e740)}}, Count:3, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.149869   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.250230   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.350641   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.453261   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.499784   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c0dea", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node vishwanath status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a741ea, ext:3663822266, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b91a6ec5b, ext:3881904370, loc:(*time.Location)(0x781e740)}}, Count:4, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.556790   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.634337   14385 controller.go:194] failed to get node "vishwanath" when trying to set owner ref to the node lease: nodes "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.657078   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.757613   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.858527   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.900053   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c3579", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node vishwanath status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a76979, ext:3663832388, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b91a763da, ext:3881934961, loc:(*time.Location)(0x781e740)}}, Count:4, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:52 vishwanath kubelet[14385]: E0813 17:26:52.959653   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:53 vishwanath kubelet[14385]: E0813 17:26:53.060248   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:53 vishwanath kubelet[14385]: E0813 17:26:53.162184   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:53 vishwanath kubelet[14385]: I0813 17:26:53.200004   14385 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 13 17:26:53 vishwanath kubelet[14385]: I0813 17:26:53.204798   14385 kubelet_node_status.go:72] Attempting to register node vishwanath
Aug 13 17:26:53 vishwanath kubelet[14385]: E0813 17:26:53.262520   14385 kubelet.go:2248] node "vishwanath" not found
Aug 13 17:26:53 vishwanath kubelet[14385]: I0813 17:26:53.314406   14385 kubelet_node_status.go:75] Successfully registered node vishwanath
Aug 13 17:26:53 vishwanath kubelet[14385]: E0813 17:26:53.316506   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c5684", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientPID", Message:"Node vishwanath status is now: NodeHasSufficientPID", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a78a84, ext:3663840849, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b91a7bcd4, ext:3881957738, loc:(*time.Location)(0x781e740)}}, Count:4, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:53 vishwanath kubelet[14385]: E0813 17:26:53.699820   14385 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"vishwanath.15ba797b195c0dea", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"vishwanath", UID:"vishwanath", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientMemory", Message:"Node vishwanath status is now: NodeHasSufficientMemory", Source:v1.EventSource{Component:"kubelet", Host:"vishwanath"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b84a741ea, ext:3663822266, loc:(*time.Location)(0x781e740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf4cc73b930e89c8, ext:3905471917, loc:(*time.Location)(0x781e740)}}, Count:5, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)
Aug 13 17:26:55 vishwanath kubelet[14385]: E0813 17:26:55.201654   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:26:56 vishwanath kubelet[14385]: W0813 17:26:56.839917   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:00 vishwanath kubelet[14385]: E0813 17:27:00.213252   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:01 vishwanath kubelet[14385]: W0813 17:27:01.841733   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:05 vishwanath kubelet[14385]: E0813 17:27:05.220129   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:06 vishwanath kubelet[14385]: W0813 17:27:06.848136   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:10 vishwanath kubelet[14385]: E0813 17:27:10.224804   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:10 vishwanath kubelet[14385]: I0813 17:27:10.798033   14385 kuberuntime_manager.go:928] updating runtime config through cri with podcidr 192.168.0.0/24
Aug 13 17:27:10 vishwanath kubelet[14385]: I0813 17:27:10.798774   14385 docker_service.go:353] docker cri received runtime config &RuntimeConfig{NetworkConfig:&NetworkConfig{PodCidr:192.168.0.0/24,},}
Aug 13 17:27:10 vishwanath kubelet[14385]: I0813 17:27:10.799178   14385 kubelet_network.go:77] Setting Pod CIDR:  -> 192.168.0.0/24
Aug 13 17:27:10 vishwanath kubelet[14385]: E0813 17:27:10.800263   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:10 vishwanath kubelet[14385]: I0813 17:27:10.899087   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy-token-hdk9l" (UniqueName: "kubernetes.io/secret/0b246b0f-4404-4f4d-93c2-dbef6ec448e1-kube-proxy-token-hdk9l") pod "kube-proxy-xsdf2" (UID: "0b246b0f-4404-4f4d-93c2-dbef6ec448e1")
Aug 13 17:27:10 vishwanath kubelet[14385]: I0813 17:27:10.899206   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "xtables-lock" (UniqueName: "kubernetes.io/host-path/0b246b0f-4404-4f4d-93c2-dbef6ec448e1-xtables-lock") pod "kube-proxy-xsdf2" (UID: "0b246b0f-4404-4f4d-93c2-dbef6ec448e1")
Aug 13 17:27:10 vishwanath kubelet[14385]: I0813 17:27:10.899274   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "lib-modules" (UniqueName: "kubernetes.io/host-path/0b246b0f-4404-4f4d-93c2-dbef6ec448e1-lib-modules") pod "kube-proxy-xsdf2" (UID: "0b246b0f-4404-4f4d-93c2-dbef6ec448e1")
Aug 13 17:27:10 vishwanath kubelet[14385]: I0813 17:27:10.899332   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy" (UniqueName: "kubernetes.io/configmap/0b246b0f-4404-4f4d-93c2-dbef6ec448e1-kube-proxy") pod "kube-proxy-xsdf2" (UID: "0b246b0f-4404-4f4d-93c2-dbef6ec448e1")
Aug 13 17:27:11 vishwanath kubelet[14385]: W0813 17:27:11.849087   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:11 vishwanath kubelet[14385]: W0813 17:27:11.997127   14385 pod_container_deletor.go:75] Container "79e8b22a8bb87b7b703d326e72bb51dd9df10a2fe0525c4c19192ae6fb68be2e" not found in pod's containers
Aug 13 17:27:15 vishwanath kubelet[14385]: E0813 17:27:15.230083   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:16 vishwanath kubelet[14385]: I0813 17:27:16.721122   14385 transport.go:132] certificate rotation detected, shutting down client connections to start using new credentials
Aug 13 17:27:16 vishwanath kubelet[14385]: W0813 17:27:16.849867   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:20 vishwanath kubelet[14385]: E0813 17:27:20.236417   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:21 vishwanath kubelet[14385]: W0813 17:27:21.852657   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:25 vishwanath kubelet[14385]: E0813 17:27:25.245534   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:26 vishwanath kubelet[14385]: W0813 17:27:26.853947   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:30 vishwanath kubelet[14385]: E0813 17:27:30.247892   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:31 vishwanath kubelet[14385]: W0813 17:27:31.855384   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:35 vishwanath kubelet[14385]: E0813 17:27:35.252350   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:36 vishwanath kubelet[14385]: W0813 17:27:36.855971   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:40 vishwanath kubelet[14385]: E0813 17:27:40.255338   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:41 vishwanath kubelet[14385]: W0813 17:27:41.857943   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:45 vishwanath kubelet[14385]: E0813 17:27:45.259806   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:46 vishwanath kubelet[14385]: W0813 17:27:46.861487   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:50 vishwanath kubelet[14385]: E0813 17:27:50.263638   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:51 vishwanath kubelet[14385]: W0813 17:27:51.869913   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:27:55 vishwanath kubelet[14385]: E0813 17:27:55.268052   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:27:56 vishwanath kubelet[14385]: W0813 17:27:56.873844   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:00 vishwanath kubelet[14385]: E0813 17:28:00.270142   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:01 vishwanath kubelet[14385]: W0813 17:28:01.874385   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:05 vishwanath kubelet[14385]: E0813 17:28:05.280361   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:06 vishwanath kubelet[14385]: W0813 17:28:06.875322   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:10 vishwanath kubelet[14385]: E0813 17:28:10.291543   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:11 vishwanath kubelet[14385]: W0813 17:28:11.883236   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:15 vishwanath kubelet[14385]: E0813 17:28:15.295161   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:16 vishwanath kubelet[14385]: W0813 17:28:16.884412   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:20 vishwanath kubelet[14385]: E0813 17:28:20.297499   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:21 vishwanath kubelet[14385]: W0813 17:28:21.885605   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:25 vishwanath kubelet[14385]: E0813 17:28:25.303118   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:26 vishwanath kubelet[14385]: W0813 17:28:26.890395   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:30 vishwanath kubelet[14385]: E0813 17:28:30.305068   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:31 vishwanath kubelet[14385]: W0813 17:28:31.892128   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:35 vishwanath kubelet[14385]: E0813 17:28:35.307604   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:36 vishwanath kubelet[14385]: W0813 17:28:36.892348   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:40 vishwanath kubelet[14385]: E0813 17:28:40.315028   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:41 vishwanath kubelet[14385]: W0813 17:28:41.894592   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:45 vishwanath kubelet[14385]: E0813 17:28:45.322834   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:46 vishwanath kubelet[14385]: W0813 17:28:46.895086   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:50 vishwanath kubelet[14385]: E0813 17:28:50.328541   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:51 vishwanath kubelet[14385]: W0813 17:28:51.896256   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:28:55 vishwanath kubelet[14385]: E0813 17:28:55.333344   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:28:56 vishwanath kubelet[14385]: W0813 17:28:56.897636   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:00 vishwanath kubelet[14385]: E0813 17:29:00.343647   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:01 vishwanath kubelet[14385]: W0813 17:29:01.898033   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:05 vishwanath kubelet[14385]: E0813 17:29:05.349236   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:06 vishwanath kubelet[14385]: W0813 17:29:06.899597   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:10 vishwanath kubelet[14385]: E0813 17:29:10.353709   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:11 vishwanath kubelet[14385]: W0813 17:29:11.902279   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:15 vishwanath kubelet[14385]: E0813 17:29:15.358596   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:16 vishwanath kubelet[14385]: W0813 17:29:16.909115   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:20 vishwanath kubelet[14385]: E0813 17:29:20.360731   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:21 vishwanath kubelet[14385]: W0813 17:29:21.910404   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:25 vishwanath kubelet[14385]: E0813 17:29:25.366303   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:26 vishwanath kubelet[14385]: W0813 17:29:26.911447   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:30 vishwanath kubelet[14385]: E0813 17:29:30.372296   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:31 vishwanath kubelet[14385]: W0813 17:29:31.912271   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:35 vishwanath kubelet[14385]: E0813 17:29:35.387584   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:36 vishwanath kubelet[14385]: W0813 17:29:36.913061   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:40 vishwanath kubelet[14385]: E0813 17:29:40.391277   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:41 vishwanath kubelet[14385]: W0813 17:29:41.914614   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:45 vishwanath kubelet[14385]: E0813 17:29:45.394628   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:46 vishwanath kubelet[14385]: W0813 17:29:46.916530   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:50 vishwanath kubelet[14385]: E0813 17:29:50.399384   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:51 vishwanath kubelet[14385]: W0813 17:29:51.917708   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:29:55 vishwanath kubelet[14385]: E0813 17:29:55.405268   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:29:56 vishwanath kubelet[14385]: W0813 17:29:56.923166   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:00 vishwanath kubelet[14385]: E0813 17:30:00.412036   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:01 vishwanath kubelet[14385]: W0813 17:30:01.927024   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:05 vishwanath kubelet[14385]: E0813 17:30:05.423143   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:06 vishwanath kubelet[14385]: W0813 17:30:06.927631   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:10 vishwanath kubelet[14385]: E0813 17:30:10.431268   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:11 vishwanath kubelet[14385]: W0813 17:30:11.928660   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:15 vishwanath kubelet[14385]: E0813 17:30:15.442826   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:16 vishwanath kubelet[14385]: W0813 17:30:16.929751   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:20 vishwanath kubelet[14385]: E0813 17:30:20.447675   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:21 vishwanath kubelet[14385]: W0813 17:30:21.930354   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:25 vishwanath kubelet[14385]: E0813 17:30:25.454722   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:26 vishwanath kubelet[14385]: W0813 17:30:26.930617   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:30 vishwanath kubelet[14385]: E0813 17:30:30.457706   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:31 vishwanath kubelet[14385]: W0813 17:30:31.936106   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:35 vishwanath kubelet[14385]: E0813 17:30:35.464147   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:36 vishwanath kubelet[14385]: W0813 17:30:36.937532   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:38 vishwanath kubelet[14385]: I0813 17:30:38.743261   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "weavedb" (UniqueName: "kubernetes.io/host-path/ae2d9175-412c-4008-b349-ecfbc3ab774e-weavedb") pod "weave-net-f8wmc" (UID: "ae2d9175-412c-4008-b349-ecfbc3ab774e")
Aug 13 17:30:38 vishwanath kubelet[14385]: I0813 17:30:38.744382   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "cni-bin" (UniqueName: "kubernetes.io/host-path/ae2d9175-412c-4008-b349-ecfbc3ab774e-cni-bin") pod "weave-net-f8wmc" (UID: "ae2d9175-412c-4008-b349-ecfbc3ab774e")
Aug 13 17:30:38 vishwanath kubelet[14385]: I0813 17:30:38.746017   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "weave-net-token-9fb8m" (UniqueName: "kubernetes.io/secret/ae2d9175-412c-4008-b349-ecfbc3ab774e-weave-net-token-9fb8m") pod "weave-net-f8wmc" (UID: "ae2d9175-412c-4008-b349-ecfbc3ab774e")
Aug 13 17:30:38 vishwanath kubelet[14385]: I0813 17:30:38.746914   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "dbus" (UniqueName: "kubernetes.io/host-path/ae2d9175-412c-4008-b349-ecfbc3ab774e-dbus") pod "weave-net-f8wmc" (UID: "ae2d9175-412c-4008-b349-ecfbc3ab774e")
Aug 13 17:30:38 vishwanath kubelet[14385]: I0813 17:30:38.748147   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "xtables-lock" (UniqueName: "kubernetes.io/host-path/ae2d9175-412c-4008-b349-ecfbc3ab774e-xtables-lock") pod "weave-net-f8wmc" (UID: "ae2d9175-412c-4008-b349-ecfbc3ab774e")
Aug 13 17:30:38 vishwanath kubelet[14385]: I0813 17:30:38.749303   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "cni-bin2" (UniqueName: "kubernetes.io/host-path/ae2d9175-412c-4008-b349-ecfbc3ab774e-cni-bin2") pod "weave-net-f8wmc" (UID: "ae2d9175-412c-4008-b349-ecfbc3ab774e")
Aug 13 17:30:38 vishwanath kubelet[14385]: I0813 17:30:38.749609   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "cni-conf" (UniqueName: "kubernetes.io/host-path/ae2d9175-412c-4008-b349-ecfbc3ab774e-cni-conf") pod "weave-net-f8wmc" (UID: "ae2d9175-412c-4008-b349-ecfbc3ab774e")
Aug 13 17:30:38 vishwanath kubelet[14385]: I0813 17:30:38.750507   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "lib-modules" (UniqueName: "kubernetes.io/host-path/ae2d9175-412c-4008-b349-ecfbc3ab774e-lib-modules") pod "weave-net-f8wmc" (UID: "ae2d9175-412c-4008-b349-ecfbc3ab774e")
Aug 13 17:30:40 vishwanath kubelet[14385]: E0813 17:30:40.471892   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:41 vishwanath kubelet[14385]: W0813 17:30:41.943496   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:45 vishwanath kubelet[14385]: E0813 17:30:45.477303   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:46 vishwanath kubelet[14385]: W0813 17:30:46.943741   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:50 vishwanath kubelet[14385]: E0813 17:30:50.480090   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:51 vishwanath kubelet[14385]: W0813 17:30:51.944524   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:30:55 vishwanath kubelet[14385]: E0813 17:30:55.495665   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:30:56 vishwanath kubelet[14385]: W0813 17:30:56.944898   14385 cni.go:213] Unable to update cni config: No networks found in /etc/cni/net.d
Aug 13 17:31:00 vishwanath kubelet[14385]: E0813 17:31:00.499712   14385 kubelet.go:2169] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Aug 13 17:31:15 vishwanath kubelet[14385]: I0813 17:31:15.793520   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/dbf15e78-80fd-4a32-b3c2-7e8064be382e-config-volume") pod "coredns-5c98db65d4-brvsz" (UID: "dbf15e78-80fd-4a32-b3c2-7e8064be382e")
Aug 13 17:31:15 vishwanath kubelet[14385]: I0813 17:31:15.793632   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "coredns-token-zhcdn" (UniqueName: "kubernetes.io/secret/dbf15e78-80fd-4a32-b3c2-7e8064be382e-coredns-token-zhcdn") pod "coredns-5c98db65d4-brvsz" (UID: "dbf15e78-80fd-4a32-b3c2-7e8064be382e")
Aug 13 17:31:15 vishwanath kubelet[14385]: I0813 17:31:15.894550   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "coredns-token-zhcdn" (UniqueName: "kubernetes.io/secret/f2a81a45-8eab-4919-995c-13629fb8012f-coredns-token-zhcdn") pod "coredns-5c98db65d4-jvxq2" (UID: "f2a81a45-8eab-4919-995c-13629fb8012f")
Aug 13 17:31:15 vishwanath kubelet[14385]: I0813 17:31:15.894633   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/f2a81a45-8eab-4919-995c-13629fb8012f-config-volume") pod "coredns-5c98db65d4-jvxq2" (UID: "f2a81a45-8eab-4919-995c-13629fb8012f")
Aug 13 17:31:17 vishwanath kubelet[14385]: W0813 17:31:17.608856   14385 pod_container_deletor.go:75] Container "fc6b1c210db100e8d5243ee7d7915ec0969e1209cde58ec00efd23819983acf9" not found in pod's containers
Aug 13 17:31:17 vishwanath kubelet[14385]: W0813 17:31:17.853873   14385 pod_container_deletor.go:75] Container "2f6474c803581ca0b03001451014ba56bd131e256c844ff29625c30266f51953" not found in pod's containers
Aug 13 17:32:08 vishwanath kubelet[14385]: E0813 17:32:08.647608   14385 reflector.go:125] object-"default"/"default-token-9nk2c": Failed to list *v1.Secret: secrets "default-token-9nk2c" is forbidden: User "system:node:vishwanath" cannot list resource "secrets" in API group "" in the namespace "default": no relationship found between node "vishwanath" and this object
Aug 13 17:32:08 vishwanath kubelet[14385]: I0813 17:32:08.740807   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-9nk2c" (UniqueName: "kubernetes.io/secret/9f0f0e98-7b7e-4a8a-a335-d3ba487bbdd4-default-token-9nk2c") pod "myimg-d6bc7b555-bgwgx" (UID: "9f0f0e98-7b7e-4a8a-a335-d3ba487bbdd4")
Aug 13 17:32:10 vishwanath kubelet[14385]: W0813 17:32:10.961470   14385 pod_container_deletor.go:75] Container "1a4a4fa3e5835696668fc6bccd47b874fd83fb4ea506fceb2d49e0b0069dc224" not found in pod's containers
Aug 13 17:35:20 vishwanath kubelet[14385]: I0813 17:35:20.948140   14385 reconciler.go:203] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-9nk2c" (UniqueName: "kubernetes.io/secret/9f400852-ce42-46d8-abc7-7863872a98bd-default-token-9nk2c") pod "fluent-ds-d874j" (UID: "9f400852-ce42-46d8-abc7-7863872a98bd")
Aug 13 17:35:22 vishwanath kubelet[14385]: W0813 17:35:22.106344   14385 pod_container_deletor.go:75] Container "d266a831cae3b1107054135dc06dfecf6d18608a6b321e3d43b859c894618f49" not found in pod's containers
Aug 13 17:35:47 vishwanath kubelet[14385]: I0813 17:35:47.467630   14385 reconciler.go:177] operationExecutor.UnmountVolume started for volume "default-token-9nk2c" (UniqueName: "kubernetes.io/secret/9f0f0e98-7b7e-4a8a-a335-d3ba487bbdd4-default-token-9nk2c") pod "9f0f0e98-7b7e-4a8a-a335-d3ba487bbdd4" (UID: "9f0f0e98-7b7e-4a8a-a335-d3ba487bbdd4")
Aug 13 17:35:47 vishwanath kubelet[14385]: I0813 17:35:47.537526   14385 operation_generator.go:860] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/9f0f0e98-7b7e-4a8a-a335-d3ba487bbdd4-default-token-9nk2c" (OuterVolumeSpecName: "default-token-9nk2c") pod "9f0f0e98-7b7e-4a8a-a335-d3ba487bbdd4" (UID: "9f0f0e98-7b7e-4a8a-a335-d3ba487bbdd4"). InnerVolumeSpecName "default-token-9nk2c". PluginName "kubernetes.io/secret", VolumeGidValue ""
Aug 13 17:35:47 vishwanath kubelet[14385]: I0813 17:35:47.567921   14385 reconciler.go:297] Volume detached for volume "default-token-9nk2c" (UniqueName: "kubernetes.io/secret/9f0f0e98-7b7e-4a8a-a335-d3ba487bbdd4-default-token-9nk2c") on node "vishwanath" DevicePath ""